In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Oppgave 1.1

a = 43 # heltall storre enn 10
b = 7 # heltall mindre enn 10
c = 18 # heltall storre enn 10
d = a*b+c
r = 2


x = np.array([])


a = str(a)
for i in range (r):
   x = np.append(x, int(a[i]))


b = str(0) + str(b)
for i in range (r):
   x = np.append(x, int(b[i]))


c = str(c)
for i in range (r):
   x = np.append(x, int(c[i]))


d = str(d)
for i in range (r):
   x = np.append(x, int(d[i]))


print(x)


y = np.array([])
for i in d:
	y = np.append(y, int(i))


print(y)

def f(x):
    length = len(x)
    z_hat = np.zeros(length)
    for i in range(len(z_hat)):
        z_hat[i] = i
    return z_hat

for i in range(r+1):
    z_hat = f(x)
    x = np.append(x, z_hat[-1])

y_hat = np.zeros(r+1)
for i in range(len(y_hat)):
    y_hat[i] = x[-(i+1)]

print (y_hat)

[4. 3. 0. 7. 1. 8. 3. 1.]
[3. 1. 9.]
[9. 8. 7.]
